### ISSUE TITLE
建议能支持返回DataSet和Table

### ISSUE THREAD

**Issue by ghd258** [Ahoo-Wang/SmartSql#12]
有些业务需要返回多个结果集，比如返回数据和查询条件下的条数，这个sql语句是一个存储过程，里面需要处理逻辑；或者有些大数据需要处理，但是数据是多个表，需要一次返回数据 如果用DataSet就非常方便

**Comment by Ahoo-Wang** [comment]
> 下一个版本增加一下四个方法支持以上特性：
- GetDataTable GetDataSet 
- GetDataTableAsync GetDataSetAsync

**Comment by Ahoo-Wang** [comment]
v3.1.0 版本已支持。
https://github.com/Ahoo-Wang/SmartSql/releases/tag/v3.1.0
