### ISSUE TITLE
能否简化下SmartSqlMapConfig.xml的配置？

### ISSUE THREAD

**Issue by RocherKong** [Ahoo-Wang/SmartSql#2]
能否简化下SmartSqlMapConfig.xml的xml配置?：
><SmartSqlMaps>
    <SmartSqlMap Path="Maps/T_Test.xml"></SmartSqlMap>
 </SmartSqlMaps>

此处能否修改为

>  <SmartSqlMaps>
    <SmartSqlMap Path="Maps/"></SmartSqlMap>
  </SmartSqlMaps>

直接以文件夹的形式提供配置项？

**Comment by Ahoo-Wang** [comment]
[https://github.com/Ahoo-Wang/SmartSql/releases/tag/v1.7.8](https://github.com/Ahoo-Wang/SmartSql/releases/tag/v1.7.8)

**Comment by Ahoo-Wang** [comment]
[https://github.com/Ahoo-Wang/SmartSql/releases/tag/v1.7.8](https://github.com/Ahoo-Wang/SmartSql/releases/tag/v1.7.8)

**Comment by RocherKong** [comment]
Nice.
