### ISSUE TITLE
IsWatchConfigFile=true时改变config内容依然无效果

### ISSUE THREAD

**Issue by yangbodevp** [Ahoo-Wang/SmartSql#21]
smartsqlmapconfig的setting节点，监视配置文件改为true之后修改配置文件无效果，从修改数据库字符串到maps里的sql语句，都没有效果。

**Comment by yangbodevp** [comment]
smartsql.DIExtensions、SmartSql  3.3.18

**Comment by yangbodevp** [comment]
SmartSql.DyRepository 3.3.12
另外我申请加群了，烦请通过一下

**Comment by Ahoo-Wang** [comment]
@yangbodevp 运行环境运行时未开启监控，之后的修改不会监控文件变化。这个应该比较好理解。
