### ISSUE TITLE
解决如果配置xml文件太多需要分类为多个文件夹来管理xml文件

### ISSUE THREAD

**Issue by ghd258** [Ahoo-Wang/SmartSql#25]
解决如果配置xml文件太多需要分类为多个文件夹来管理xml文件

![qq 20180725165635](https://user-images.githubusercontent.com/4811375/43190619-10b1c900-902c-11e8-920f-1271c9e1ad52.jpg)

**Comment by Ahoo-Wang** [comment]
[v3.5.2](https://github.com/Ahoo-Wang/SmartSql/releases/tag/v3.5.2)
