### ISSUE TITLE
增加嵌套实体的多sql多表更新功能，并默认使用事务

### ISSUE THREAD

**Issue by ElderJames** [Ahoo-Wang/SmartSql#26]
主要用于有“实体内直接引用实体”模型的聚合的整体更新。这种类型的模型在DDD中普遍存在，而且聚合内强一致性，需要使用事务更新， 希望DyRepository中可以实现。

仓储方法实现多实体参数和嵌套实体，xml中支持多语句事务执行。这在联表更新非常有用！

**Comment by ElderJames** [comment]
事务可以默认开启，加一个可选属性选择不使用


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/SmartSql/releases/tag/v3.6.8

**Comment by ElderJames** [comment]
excellent
