### ISSUE TITLE
增加批量新增，修改功能

### ISSUE THREAD

**Issue by ghd258** [Ahoo-Wang/SmartSql#27]
1 批量新增功能   全部新增
2 批量更新功能   全部更新
3 同时用新增和更新功能，根据是否数据库已经存在记录 存在的更新 不存在的新增
（注：更新是有参数设置每批次的条数，比如一次更新100万条 这种数据太大，可以分为数据块  比如每批次5000条执行一次sql脚本）
mysql有批量新增更新语法 比较好用，虽然sql server也有批量功能单不如mysql强大 ，可以参考这个组件http://bulk-operations.net/

**Comment by Ahoo-Wang** [comment]
请使用For标签。
