### ISSUE TITLE
Is it good idea?

### ISSUE THREAD

**Issue by Oleg26Dev** [Ahoo-Wang/SmartSql#3]
I ma sure you understand that it is incorrect in the common case

<Statement Id="Insert">
      INSERT INTO T_Test
      (Name)
      VALUES
      (@Name)
      **;Select @@IDENTITY**
    </Statement>

**Comment by Ahoo-Wang** [comment]
Thank you for reminding me. https://github.com/Ahoo-Wang/SmartSql/commit/347a19dd2ab6457b398a4522319d70d2128b127f

**Comment by Oleg26Dev** [comment]
Yes, it is correct, thanks
