### ISSUE TITLE
新增全局xml模板配置，包括*map和statement

### ISSUE THREAD

**Issue by ElderJames** [Ahoo-Wang/SmartSql#30]
在有框架和设计规范约束的情况下，一些可复用的场景比如分页，MultipleResultmap和包含排序、limit等都可以全局共用。

 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by ElderJames** [comment]
还有一些联表查询得出结果的，有可能会用到相同的resultmap

**Comment by Ahoo-Wang** [comment]
[v3.7.0-pre](https://www.nuget.org/packages/SmartSql/3.7.0-pre)
