### ISSUE TITLE
建议debug生成的SQL文直接能够复制到SQL开发工具进行执行调试

### ISSUE THREAD

**Issue by bryanli2018** [Ahoo-Wang/SmartSql#35]
目前生成的SQL文还需要手工把参数替换掉才可执行调试，开发效率不高。建议log拼接出来的SQL是直接将参数替换掉。

**Comment by ElderJames** [comment]
已实现

**Comment by bryanli2018** [comment]
参数为字符型时，拼接出来的SQL不正确，缺少单引号。。

**Comment by Ahoo-Wang** [comment]
@bryanli2018 ok,今晚处理。

**Comment by Ahoo-Wang** [comment]
[v3.6.8.2](https://www.nuget.org/packages/SmartSql/3.6.8.2)
