### ISSUE TITLE
Feature Request：Insert/Update自动分析实体字段生成sql，并支持可配置ParameterMap

### ISSUE THREAD

**Issue by ElderJames** [Ahoo-Wang/SmartSql#38]
类似dapper.contrib的做法

**Comment by Ahoo-Wang** [comment]
@ElderJames Insert/Update 可以自动翻译成sql，但是ParamterMap如何跟自动翻译的sql对应呢？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by ElderJames** [comment]
跟SqlId一样加个MapId参数？

**Comment by Ahoo-Wang** [comment]
合并到 https://github.com/Ahoo-Wang/SmartSql/issues/46
