### ISSUE TITLE
多个文件Scope重复时，抛出异常且异常提示不准确

### ISSUE THREAD

**Issue by ElderJames** [Ahoo-Wang/SmartSql#43]
版本号：3.7.15
重现方法：两个文件，Scope相同，SqlId不重复。

1. 不确定抛出异常是否预期。
2. 异常提示与Scope相同无关
![image](https://user-images.githubusercontent.com/7550366/47514261-80b62880-d8b2-11e8-9e16-d5d7f164385a.png)

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/SmartSql/commit/cf004db60f4456fcfc806ef294cf882d0aeeb97b
