### ISSUE TITLE
新版本意见

### ISSUE THREAD

**Issue by sharpleafage** [Ahoo-Wang/SmartSql#7]
1.去除缓存功能，提高性能，java中的mybatis，很多人操作缓存还是放在service层，有自定义的规则，或者微服务中，有服务接口缓存，
2.xml标签简单化，建议按照新的java中mybatis中的标签来设计，比如 <trim prefix="VALUES (" suffix=")" suffixOverrides=","> <if test="_parameter != null">  <set>等等
3.按照规则，来调用sqlmapper，而不是大量重复代码，比如
SqlMapper.ExecuteScalar<long>(new RequestContext
                {
                    Scope = "T_Test",
                    SqlId = "Insert",
                    Request = new { Name = $"Name-{preId}", TableName = "T_Test1" }
                });
  Scope， SqlId  通过规则可以封装scope sqlid，只需传入参数即可，参数类型

**Comment by Ahoo-Wang** [comment]
1. 去除缓存不会提高性能，数据访问层缓存有一定的需求，如果要的好的话可以解决很大部分问题，so 不采纳该建议。
2. xml 标签目前基本与MyBatis用法一致
3. V3.0 将新增 动态仓储接口实现解决，简化用户代码量 

详情参见 #9
