### ISSUE TITLE
SmartSql-v3.0 意见收集

### ISSUE THREAD

**Issue by Ahoo-Wang** [Ahoo-Wang/SmartSql#9]
# SmartSql-v3.0 意见收集
## v3.0 已知主要目标：
1. 增强SmartSql扩展性
2. 重构部分代码
3. 去除Dapper依赖
4. 优化缓存触发策略
5. 仓储接口动态实现
6. 以及各位的意见，请在此Issue中评论新增意见

> SmartSql 的成长离不开大家的意见&建议，感谢各位对SmartSql的支持！

**Comment by Ahoo-Wang** [comment]
新增 Insert / Update / Select / Delete 强语义化标签

**Comment by ywj6792341** [comment]
能否增加像 EF 的 CodeFirst 一样的管理数据库的方式。根据Model智能生成数据库结构。

**Comment by Ahoo-Wang** [comment]
@ywj6792341 SmartSql 的设计宗旨并不是 CodeFirst ，而是希望开发人员更多的了解Sql，对Sql拥有绝对的控制权，以获得灵活性与性能。所以该建议不能采纳，不过还是感谢你的参与，让SmartSql可以变得更好。

**Comment by ElderJames** [comment]
类似ibatis的TypeHandlder实现，用来对特定类型的字段进行读写前后的转换。如json、xml。
建议自带几个常用的序列化器，再提供接口给使用者自己实现，并通过key来注册到smarsql中。而模板中使用字段上的属性type=“key”来标识，如赋值 `Images= [@images,Type="json"]`，读取`SELECT [Images,Type="json"] FROM...` 可以把这个特性的名称改成vue、angular里的指令。
